"""odebran sloupec u consolation_tabulky

Revision ID: 34fd2fcc0527
Revises: f81fa481093d
Create Date: 2026-09-15 14:27:41.912514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fd2fcc0527'
down_revision = 'f81fa481093d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consolation_stats', schema=None) as batch_op:
        batch_op.drop_column('points_gained')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consolation_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_gained', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
