"""přidání sloupců total_player a total_player_in_playoff

Revision ID: 6d004236ca3f
Revises: 035a7987023f
Create Date: 2026-09-08 15:20:04.873847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d004236ca3f'
down_revision = '035a7987023f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_players', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_players_in_playoff', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tournament_winner', 'players', ['winner_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournament_winner', type_='foreignkey')
        batch_op.drop_column('total_players_in_playoff')
        batch_op.drop_column('total_players')

    # ### end Alembic commands ###
