"""nova db

Revision ID: 80b281b3db0e
Revises: 
Create Date: 2026-08-29 15:25:23.573002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b281b3db0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('matches_won', sa.Integer(), nullable=True),
    sa.Column('matches_lost', sa.Integer(), nullable=True),
    sa.Column('matches_drawn', sa.Integer(), nullable=True),
    sa.Column('tournaments_played', sa.Integer(), nullable=True),
    sa.Column('sum_of_ranks', sa.Integer(), nullable=True),
    sa.Column('last_rank', sa.Integer(), nullable=True),
    sa.Column('last_tournament_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('group_match_format', sa.Integer(), nullable=True),
    sa.Column('playoff_match_format', sa.Integer(), nullable=True),
    sa.Column('advance_per_group', sa.Integer(), nullable=True),
    sa.Column('group_elimination_action', sa.String(length=50), nullable=True),
    sa.Column('playoff_elimination_action', sa.String(length=50), nullable=True),
    sa.Column('has_consolation', sa.Boolean(), nullable=True),
    sa.Column('consolation_format', sa.String(length=50), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], name='fk_tournament_winner', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('bracket_type', sa.String(length=50), nullable=True),
    sa.Column('is_consolation', sa.Boolean(), nullable=True),
    sa.Column('tree_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_consolation', sa.Boolean(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('group_seed', sa.String(length=10), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('global_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['global_player_id'], ['global_players.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('match_format', sa.String(length=50), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('is_in_progress', sa.Boolean(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('bracket_id', sa.Integer(), nullable=True),
    sa.Column('player_a_id', sa.Integer(), nullable=True),
    sa.Column('player_b_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(group_id IS NOT NULL AND bracket_id IS NULL) OR (group_id IS NULL AND bracket_id IS NOT NULL)', name='check_match_belongs_to_exactly_one_place'),
    sa.ForeignKeyConstraint(['bracket_id'], ['brackets.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['player_a_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_b_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('games_win', sa.Integer(), nullable=True),
    sa.Column('games_lost', sa.Integer(), nullable=True),
    sa.Column('balls_win', sa.Integer(), nullable=True),
    sa.Column('balls_lost', sa.Integer(), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_results')
    op.drop_table('player_stats')
    op.drop_table('matches')
    op.drop_table('players')
    op.drop_table('groups')
    op.drop_table('brackets')
    op.drop_table('tournaments')
    op.drop_table('global_players')
    # ### end Alembic commands ###
