"""nové sloupce pro zápas

Revision ID: 83f67c46d5e4
Revises: 15224191111b
Create Date: 2026-09-26 14:39:54.676858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f67c46d5e4'
down_revision = '15224191111b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed_a', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('seed_b', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('seed_b')
        batch_op.drop_column('seed_a')

    # ### end Alembic commands ###
