"""noný sloupec has_playoff

Revision ID: a2b6b46b2350
Revises: 83f67c46d5e4
Create Date: 2026-09-26 15:41:27.816371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b6b46b2350'
down_revision = '83f67c46d5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_playoff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('has_playoff')

    # ### end Alembic commands ###
