"""vytvořeny sloupce pro PlayoffStats

Revision ID: d85e593b692d
Revises: 27ec04c093e6
Create Date: 2026-09-09 16:28:32.510733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85e593b692d'
down_revision = '27ec04c093e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playoff_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_win', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_lost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balls_win', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balls_lost', sa.Integer(), nullable=True))

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tournament_winner', 'players', ['winner_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournament_winner', type_='foreignkey')

    with op.batch_alter_table('playoff_stats', schema=None) as batch_op:
        batch_op.drop_column('balls_lost')
        batch_op.drop_column('balls_win')
        batch_op.drop_column('games_lost')
        batch_op.drop_column('games_win')

    # ### end Alembic commands ###
