"""přidan sloupec location,tournament_format, include_in_global_stats

Revision ID: ed8bc3869b03
Revises: a2b6b46b2350
Create Date: 2026-10-09 15:04:31.858963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8bc3869b03'
down_revision = 'a2b6b46b2350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('tournament_format', sa.String(length=50), server_default='groups_playoff', nullable=False))
        batch_op.add_column(sa.Column('include_in_global_stats', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('include_in_global_stats')
        batch_op.drop_column('tournament_format')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
