"""zrušen total_points a nahrazen dynamické počítání bodů

Revision ID: f4a2d435d9f6
Revises: 4e4c44430c8e
Create Date: 2026-09-15 16:11:44.292349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a2d435d9f6'
down_revision = '4e4c44430c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_players', schema=None) as batch_op:
        batch_op.drop_column('total_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
