"""pridan relationship na vítěze

Revision ID: f81fa481093d
Revises: 0df4f2c21b41
Create Date: 2026-09-10 18:32:06.422429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81fa481093d'
down_revision = '0df4f2c21b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tournament_winner', 'players', ['winner_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournament_winner', type_='foreignkey')

    # ### end Alembic commands ###
