name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/projects/tournament_app
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            flask --app run.py db upgrade
            sudo systemctl restart spravaturnaje

      - name: Send Discord Notification (Success)
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "🚀 Úspěšně nasazena nová verze turnajové apky (`spravaturnaje.cz`)!"

      - name: Send Discord Notification (Failure)
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "❌ Pozor! Deploy turnajové apky (`spravaturnaje.cz`) selhal! 😢"